name: ft_patch_package
description: >-
  Patch Flutter & Dart packages like React Native's patch-package.
  Create portable patches, store in version control, apply after pub get.
version: 1.0.0
homepage: https://github.com/buivietphi/ft_patch_package
repository: https://github.com/buivietphi/ft_patch_package

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0

executables:
  ft_patch_package: ft_patch_package
